name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  quiver: ^3.0.1
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  ternarytreap:
    path: ../../ternarytreap
