name: ternarytreap
description: Self balancing ternary tree. Optimised for autocompletion tasks. A generic Map with fast prefix and near neighbour searching on keys.
version: 1.0.6
homepage: https://github.com/derbec/ternarytreap

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  effective_dart: ^1.2.0
  pedantic: ^1.9.0
  test: ^1.6.0
