name: ternarytreap
description: Self balancing ternary tree. A generic MultiMap with fast prefix and near neighbour searching on keys.
version: 2.0.5
homepage: https://github.com/derbec/ternarytreap

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8

