name: ternarytreap
description: Self balancing ternary tree. A generic MultiMap with fast prefix and near neighbour searching on keys.
version: 1.0.8
homepage: https://github.com/derbec/ternarytreap

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.9.1
  test: ^1.15.2
